<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Kode Voucher</name>
   <tag></tag>
   <elementGuidId>56f1f900-919c-49bd-ab38-00a935dd5397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='event_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0368acc-1231-4fcb-813e-8decec651caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EventCode</value>
      <webElementGuid>bdce7c44-0d71-4e8d-b406-42b3661462aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d94fcce7-194a-4e80-a01a-14fa8e1eb78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event_code</value>
      <webElementGuid>3cccc8ca-684c-4123-bb7e-a16086435847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control kgm__form--input w-100</value>
      <webElementGuid>34df949c-31f8-427e-841d-2be8a615f766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kode Voucher Bunda*</value>
      <webElementGuid>122b521f-0252-49e3-a586-145d76b6d041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event_code&quot;)</value>
      <webElementGuid>a57d8708-723c-4105-bacf-c38677dead51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='event_code']</value>
      <webElementGuid>8ed44c54-7056-474c-8960-6c6974dd8a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-unique-code']/div[5]/input</value>
      <webElementGuid>397eb992-e112-485c-8cf9-93b266caa0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>70a8c00c-cd61-44d5-b665-8220bcd6a90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EventCode' and @type = 'text' and @id = 'event_code' and @placeholder = 'Masukkan Kode Voucher Bunda*']</value>
      <webElementGuid>bac5f385-e057-40b7-b9b7-1d39aad041c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
