<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>X</name>
   <tag></tag>
   <elementGuidId>59543160-f8b5-4d70-85d4-89e6ac00c866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sfToolbarHideButton-9309e5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='hide-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de3f5589-b03d-4a2d-b955-d9590e043fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hide-button</value>
      <webElementGuid>a5ddc136-fe01-416a-9ff4-5f567d3ddcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sfToolbarHideButton-9309e5</value>
      <webElementGuid>9c679a80-1e23-4744-8f4f-77d6bda036ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close Toolbar</value>
      <webElementGuid>36839a34-59f1-4360-b4fc-23552d110c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b1266a1a-7623-43b2-a089-1da3a0649046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>D</value>
      <webElementGuid>04bd22ce-fe97-46bf-a3c2-bbbd08f32034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sfToolbarHideButton-9309e5&quot;)</value>
      <webElementGuid>c178a85b-401e-45be-ae9b-c67bf205d2e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sfToolbarHideButton-9309e5']</value>
      <webElementGuid>c3fd9eea-baa5-4a6d-92b4-4ad1340e1443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sfToolbarMainContent-9309e5']/a</value>
      <webElementGuid>3ff3c615-d0e4-40ba-9178-a3228becd954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Symfony Support Channels'])[1]/following::a[1]</value>
      <webElementGuid>31d15f26-e883-4353-92b9-f4798f9a9f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[2]</value>
      <webElementGuid>dd378fb1-2abb-4b77-9667-c87b51c19713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/a</value>
      <webElementGuid>2456e2f9-73db-4149-b51b-d9c499de9ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sfToolbarHideButton-9309e5' and @title = 'Close Toolbar']</value>
      <webElementGuid>aae14b00-29ac-45af-a080-a213cea51aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
