<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Daftar</name>
   <tag></tag>
   <elementGuidId>1cb1d2df-18c6-4ce0-89fd-c0f7304ec9b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-new-kgm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='register-new-kgm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccf92743-d892-4f5a-bb42-654764fa02b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7f2f0c51-ecd0-4bb0-8fbc-b769987e1596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary full-width font-capitalize</value>
      <webElementGuid>5e447123-8a42-4e94-b228-87481e4d29b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-new-kgm</value>
      <webElementGuid>bfe2caf8-c9b3-4cf1-83a7-af79f77a3128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Daftar
                    </value>
      <webElementGuid>d768928d-bfcd-47fe-b9a9-aca8e83c32d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-new-kgm&quot;)</value>
      <webElementGuid>ad778407-7e6d-40da-9bfc-6cedbad89a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='register-new-kgm']</value>
      <webElementGuid>645617b6-e085-44ed-a3e7-149da55e5886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[10]/button</value>
      <webElementGuid>4770c3e6-fee9-4dbb-9efd-740aa7d6428a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie'])[1]/following::button[1]</value>
      <webElementGuid>8b6ec873-9359-41d1-8f36-450d7ca8345d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[1]</value>
      <webElementGuid>2abbef67-b183-4d66-a2ca-5c5a486cf7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari lebih lanjut.'])[1]/preceding::button[1]</value>
      <webElementGuid>1bb0d949-b976-410f-9daf-970afd0a0a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[4]/preceding::button[1]</value>
      <webElementGuid>75da5cce-fb6f-479d-8b8e-d11539b0c586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button</value>
      <webElementGuid>e013f823-3645-4a8e-92e8-d52fda104f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'register-new-kgm' and (text() = '
                        Daftar
                    ' or . = '
                        Daftar
                    ')]</value>
      <webElementGuid>072b9482-1528-45e7-b1ef-90bde40ce5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
