<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check box saya telah membaca ___</name>
   <tag></tag>
   <elementGuidId>fa4de59a-59d9-40a3-9aa6-c17cf2a3d528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sayasetuju</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sayasetuju']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>240a732b-637f-4523-9338-d8de60c45077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8ee32e38-a4cb-4498-a632-4b8645ec713e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15e93d29-c797-439f-a0fa-41d6cc89295d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sayasetuju</value>
      <webElementGuid>5e9967bf-ecb9-4384-991b-0c1ad74364ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sayasetuju&quot;)</value>
      <webElementGuid>67f61cba-3235-4d8d-8234-d61e9a1ffd7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sayasetuju']</value>
      <webElementGuid>3a8847c9-dbc0-4066-95d1-2a88e314b1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[10]/div/input</value>
      <webElementGuid>e094c635-af74-45d9-b335-22e42380dc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>632a44bf-983d-447b-9b8e-126fc3533c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sayasetuju']</value>
      <webElementGuid>04913673-e582-4403-b9cb-d014e32cc345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
