<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Kode Referal (opsional)</name>
   <tag></tag>
   <elementGuidId>fc984e3d-26db-4d08-896c-6b9619afe249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_referal_kode_event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_referal_kode_event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>666eb78c-2a20-46c0-915d-7d1ae12c729b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48cd58fb-9202-42c6-9716-2de720c870af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a09da36b-9299-420c-8173-c0f602078d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_referal_kode_event</value>
      <webElementGuid>69ffa3c4-f55c-4d36-bf21-96d9fe564b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refferal_code_event_code</value>
      <webElementGuid>64296c8c-95cb-41fe-892e-195386f0ee7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kode Referal Teman Anda Disini</value>
      <webElementGuid>580821b5-2068-4248-863f-bbe2a42bda0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_referal_kode_event&quot;)</value>
      <webElementGuid>43cffcfa-b2d3-4049-9b23-243ff0776602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_referal_kode_event']</value>
      <webElementGuid>fa8d69d8-0c78-4ea3-8883-6e84344abfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kode_referal_kode_event_area']/input</value>
      <webElementGuid>803529d1-7d34-4e62-b4f5-449726f17d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>98d499e9-c68c-4bb7-bbb0-d8889e093378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kode_referal_kode_event' and @name = 'refferal_code_event_code' and @placeholder = 'Masukkan Kode Referal Teman Anda Disini']</value>
      <webElementGuid>8b887477-53de-4388-b4fb-927420621242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
