<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Nama Lengkap</name>
   <tag></tag>
   <elementGuidId>d7d44581-1fee-4dd1-a0b8-edcef6e4cf60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namalengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namalengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3c3a297-a663-4e3d-a67b-609b4b38458e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>33b4c15a-be20-46d9-ac83-a686bd30b2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d64af5aa-c499-43bf-ad67-75a1f62ecb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namalengkap</value>
      <webElementGuid>8dccc963-e0ac-4170-b5c0-b8f2e9ae0559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5fcb508-a20c-4dfe-a57f-9c69b2bec622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mohon Isikan Nama Lengkap Bunda</value>
      <webElementGuid>16a2abd1-36eb-47dc-81a9-b7df6fca9548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namalengkap&quot;)</value>
      <webElementGuid>dd469ad5-8220-4f4a-a415-f7c4f7c0ee3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namalengkap']</value>
      <webElementGuid>713d82a8-ebe1-4fd8-9a87-f01b45242322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div/input[3]</value>
      <webElementGuid>883bb4b5-9415-44ba-8873-ae59524b39b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>d55a43c9-f2b3-4e62-b967-740089d40658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'firstname' and @type = 'text' and @id = 'namalengkap' and @placeholder = 'Mohon Isikan Nama Lengkap Bunda']</value>
      <webElementGuid>c514131f-6578-40a8-862a-ee6c8df31e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
