<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Nomor Ponsel</name>
   <tag></tag>
   <elementGuidId>f39d60b7-720a-43f9-b0e6-30f24a96eba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6b75242-4e77-4327-8ac5-032d10077356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>msisdn</value>
      <webElementGuid>c65ce748-dde0-407f-9dcc-10a2dbd4f08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b22eb56-28f4-4822-939c-aba805e24c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>5c9a6120-30b2-4047-a4b9-8100b8ef6e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c79e82a-a60d-4284-997f-1ab06d39b89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mohon Isikan Nomor Ponsel Bunda</value>
      <webElementGuid>4d5ff753-7857-48e6-b579-d2a7f7e6a068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;handphone&quot;)</value>
      <webElementGuid>49992929-bf54-4f66-98db-ce488f744958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='handphone']</value>
      <webElementGuid>e72879a9-8569-4ea5-9a69-04d9b4577cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[2]/input</value>
      <webElementGuid>41d74e14-10e2-4f99-81b6-5f80c456e126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5ec6b21b-4a6b-46c0-b36a-51943181320f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'msisdn' and @type = 'text' and @id = 'handphone' and @placeholder = 'Mohon Isikan Nomor Ponsel Bunda']</value>
      <webElementGuid>ece7669e-3678-4e03-87f3-304a06462f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
