<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Kode Event (opsional)</name>
   <tag></tag>
   <elementGuidId>7a9dc065-bdf4-4db7-bac0-79022647aa8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_referal_kode_event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_referal_kode_event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb48188f-afd0-4dc0-8cb3-706c5f5eac5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e39f9494-2b31-4674-9e6e-e517b065b1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96319155-c466-4650-ada1-32d15180aaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_referal_kode_event</value>
      <webElementGuid>2243b491-9e8d-427b-badf-79db32e355a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refferal_code_event_code</value>
      <webElementGuid>08ef7885-f2c3-4e81-b5e5-3995c1c9d4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kode Event Disini</value>
      <webElementGuid>081ff613-92bb-4cc0-9556-78166e7a2309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_referal_kode_event&quot;)</value>
      <webElementGuid>429f7949-abc4-434d-bb3b-e6539c3c1093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_referal_kode_event']</value>
      <webElementGuid>e5d00fce-d2eb-46fb-9c70-f416994c3aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kode_referal_kode_event_area']/input</value>
      <webElementGuid>8a9ebfbc-bda6-4d53-ad23-fddd5bdadc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>aa6fa6f4-aa3c-4222-8ada-0b018e50af84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kode_referal_kode_event' and @name = 'refferal_code_event_code' and @placeholder = 'Masukkan Kode Event Disini']</value>
      <webElementGuid>21235735-8b86-437e-a220-1e9aca9326d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
