<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Tanggal Lahir Anak</name>
   <tag></tag>
   <elementGuidId>863fd556-a852-442e-bfdf-c42f4a46c341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1715706779504</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='form-control reg-calendar must-field hasDatepicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dfe08f4-2181-4713-b39f-e87b59d2cbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e68ee68-723a-4bac-8d86-b46168c83695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control reg-calendar must-field hasDatepicker</value>
      <webElementGuid>fdff2120-4883-4045-bfe1-10616587b065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 15-12-2019</value>
      <webElementGuid>02ed2ac1-e08c-4599-a34d-c4990840aad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1715706779504</value>
      <webElementGuid>d00ebcb8-ae80-4916-a8a4-bc264099ec37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1715706779504&quot;)</value>
      <webElementGuid>c1b62bcd-1afa-42e1-8f2f-c530bbe8eb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1715706779504']</value>
      <webElementGuid>76a2a20b-9177-40f3-9278-e314f22a949e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='child']/div/div/input</value>
      <webElementGuid>5c3d45cd-12ee-434d-a140-53985b83fba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>6b9672de-a79e-4756-84ec-448b99e957c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Contoh: 15-12-2019' and @id = 'dp1715706779504']</value>
      <webElementGuid>c68685a6-ebb0-4dd8-be59-03d1d3749b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
