<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button TukarPoin</name>
   <tag></tag>
   <elementGuidId>4e234273-4bb4-4061-86b6-a961fd4be9cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_redeem_catalogue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_redeem_catalogue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40a89912-0c79-456e-8566-7ad964a95fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6a5d3ee-3b2a-4a4f-acc7-34a37f3ffc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>a4594f32-5463-4482-a434-9a5552c52d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_redeem_catalogue</value>
      <webElementGuid>4d5a74b1-f9a8-41f9-ad69-dfac3b218c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tukar Poin</value>
      <webElementGuid>6df4f315-8bf5-4c65-ac03-b7e747dcaf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redeemPoint('VUZveA==','','SGM-0043597','6285784018007', 'Not');</value>
      <webElementGuid>64fdc260-ec38-41b9-9ea5-f98f5dcde6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Tukar Poin
                                            </value>
      <webElementGuid>6ab228c3-623c-4511-adb4-0e1c6a2db2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_redeem_catalogue&quot;)</value>
      <webElementGuid>8d77e26a-324c-4bda-95b0-f5eda0c32db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_redeem_catalogue']</value>
      <webElementGuid>ec647913-6cfa-4bbc-8111-a893e9a1707c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_redeem_catalogue']/div[2]/div[8]/div/button</value>
      <webElementGuid>f8432277-7906-4ead-980b-dc1378aab1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Kolom Yang Kosong'])[1]/following::button[1]</value>
      <webElementGuid>c3a5e3cb-ecd4-4f34-b62c-9151e767e9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/following::button[1]</value>
      <webElementGuid>0f19f170-012d-4150-aac7-2c51c66d4996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Kolom Yang Kosong'])[2]/preceding::button[1]</value>
      <webElementGuid>63efd21c-3a9a-4883-9652-f56661919a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari lebih lanjut.'])[1]/preceding::button[1]</value>
      <webElementGuid>51fe66cb-6ca3-49bb-8547-e3c2e43553ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/button</value>
      <webElementGuid>5747ae04-b0b1-47c5-96df-f0419bf2c01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_redeem_catalogue' and @title = 'Tukar Poin' and (text() = '
                                                Tukar Poin
                                            ' or . = '
                                                Tukar Poin
                                            ')]</value>
      <webElementGuid>0135dd6b-e05d-4c95-9be5-7d5736601c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
