<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Nomor Handphone</name>
   <tag></tag>
   <elementGuidId>284b5021-3fab-436a-9b61-c793b9207f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f3d0dc8-e9d5-480f-a0f9-60dc7ef8bb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>msisdn</value>
      <webElementGuid>56149235-088f-4bd8-b6c1-adeafa650268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c803caa-0ea0-4f3c-941e-9c875f593fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-number</value>
      <webElementGuid>894d10d8-c0cc-445e-b0b9-990afc6cfe0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control kgm__form--input w-100</value>
      <webElementGuid>67528a40-2153-4d2b-9b0b-ecaf1449991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nomor Handphone</value>
      <webElementGuid>0d3e0765-b21d-4fec-b62e-333c7b4f5500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-number&quot;)</value>
      <webElementGuid>40d7fa39-bc23-47a9-9d15-1246bb478179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-number']</value>
      <webElementGuid>b92cb9d3-29c7-4213-b71e-9170bd7a0f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login']/div[2]/input[2]</value>
      <webElementGuid>2c8c89a4-0ad2-459d-867e-760999774d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>b740ec08-e9df-425b-ae90-1e36f27b151e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'msisdn' and @type = 'text' and @id = 'phone-number' and @placeholder = 'Masukkan Nomor Handphone']</value>
      <webElementGuid>19705a6a-db5f-4f29-9d0e-85da6e6b50e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
