<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Kecamatan</name>
   <tag></tag>
   <elementGuidId>3cfc0339-bfb3-4273-9c89-fdd9320f5d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subdistrict</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='subdistrict']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5fcbae44-82af-40f2-a3ef-9f0a0e0e0077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subdistrict</value>
      <webElementGuid>b0987465-3078-4033-99da-62089891b21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subdistrict</value>
      <webElementGuid>39c41026-df87-4f6b-8a6b-3cdedc9183aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c7d2e804-a599-41ea-9998-4929336c79de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subdistrict&quot;)</value>
      <webElementGuid>743c3c3e-86d5-45a4-b376-c0b5af34fb04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='subdistrict']</value>
      <webElementGuid>cc31cc8a-fd66-46ea-9be3-4c2231df4986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_redeem_catalogue']/div[2]/div[6]/select</value>
      <webElementGuid>4b0aaed5-f4b7-4030-94a8-8b4c62252184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[1]</value>
      <webElementGuid>2a5f3e6f-adf7-49da-9e03-7d106ce2c339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten/Kotamadya'])[1]/following::select[2]</value>
      <webElementGuid>44c5ab38-8e06-4fca-a4a7-e19fd0a12dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/preceding::select[1]</value>
      <webElementGuid>9cb572ff-0697-4ad5-bafc-149c1efe944b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Kolom Yang Kosong'])[1]/preceding::select[2]</value>
      <webElementGuid>ec7055d6-29cd-4cf5-a4db-7168a409e67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>92652536-0349-46ae-8e75-80482146b44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'subdistrict' and @id = 'subdistrict']</value>
      <webElementGuid>6073bf47-b540-4a0e-af39-c4be1bc3d4cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
