<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Kelurahan</name>
   <tag></tag>
   <elementGuidId>596b246d-eccd-420a-a0ed-9315d66fd965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#village</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='village']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4f3aa5b3-0e66-424e-a710-07a90a6c03b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>village</value>
      <webElementGuid>f1e26663-5b8e-4b72-828e-717f44ff190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>village</value>
      <webElementGuid>604a883c-bf3f-4fc6-aee0-eae5adcbf95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e3d5a1a-94a5-4231-a5b6-54540e11e66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;village&quot;)</value>
      <webElementGuid>00b3c9ab-17e0-4af2-948b-1aff295591c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='village']</value>
      <webElementGuid>e561e586-878e-4222-a1ad-625355acf67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_redeem_catalogue']/div[2]/div[7]/select</value>
      <webElementGuid>8628bf8b-eae0-4810-b47a-1e2e8bbd920d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/following::select[1]</value>
      <webElementGuid>8fb8dafd-58e5-410d-b405-01e5a3c16b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[2]</value>
      <webElementGuid>47c474b4-7343-4c06-9c3f-fc9966c20c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Kolom Yang Kosong'])[1]/preceding::select[1]</value>
      <webElementGuid>63d1034c-016d-41da-9ca1-01efb99546b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tukar Poin'])[3]/preceding::select[1]</value>
      <webElementGuid>01f4e99d-106e-4cff-a6da-8a404b77a1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>ea5ec5dc-52ec-4b4e-b5aa-f89f89584fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'village' and @id = 'village']</value>
      <webElementGuid>5d22ab4d-09d7-4270-a616-89605fc071fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
